name: Perform a translation by batch
on:
  push:

jobs:
  codex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup env.
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential python3
          sudo apt-get install -y python3-pip
      - name: Run Codex
        id: run_codex
        uses: openai/codex-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            L'objectif est de traduire les fichiers po/xliff du français vers l'anglais.

            Voici les instructions:
            - ... (à compléter)

      - name: Perform commit
        run: |
          git config --global user.name "github-codex"
          git config --global user.email "Yves Chevallier"
          git add ...
          git commit -m "chore: translate fr -> en"
          git push